# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# Bart Couvreur <bercie23@yahoo.com>, 2005.
# Peter van Egdom <p.van.egdom@gmail.com>, 2003, 2004, 2005, 2006, 2007.
# Petit Gregory <thunderbirds@pandora.be>, 2003.
msgid ""
msgstr ""
"Project-Id-Version: Spacewalk\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2025-04-25 09:41+0200\n"
"PO-Revision-Date: 2011-03-04 16:08+0000\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: Dutch (http://www.transifex.com/projects/p/fedora/language/"
"nl/)\n"
"Language: nl\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: ../server/apacheAuth.py:72
#, python-format
msgid "incomplete proxy authentication token: %s"
msgstr ""

#: ../server/apacheAuth.py:103
#, python-format
msgid "Sent proxy signature %s does not match ours %s."
msgstr ""

#: ../server/apacheAuth.py:142
msgid "declined proxy authentication"
msgstr ""

#: ../server/apacheRequest.py:67
#, python-format
msgid "Invalid request received (%s)."
msgstr ""

#. Send the message as a fault.
#: ../server/apacheRequest.py:126
#, python-format
msgid ""
"IMPORTANT MESSAGE FOLLOWS:\n"
"%s"
msgstr ""

#: ../server/apacheRequest.py:156
#, python-format
msgid ""
"While running '%s': caught\n"
"%s : %s\n"
msgstr ""

#. pylint: disable-next=consider-using-f-string
#: ../server/apacheRequest.py:671
#, python-format
msgid "Invalid URI %s"
msgstr ""

#: ../server/handlers/app/packages.py:220
#, python-format
msgid ""
"\n"
"                   %s Account has been deactivated on this server.\n"
"                   Please contact your Org administrator for more help."
msgstr ""

#: ../server/handlers/xmlrpc/proxy.py:71
#, python-format
msgid ""
"SUSE Multi-Linux Manager Proxy service not enabled for server profile: \"%s\""
msgstr ""

#: ../server/handlers/xmlrpc/proxy.py:94
msgid "Invalid session key"
msgstr ""

#: ../server/handlers/xmlrpc/proxy.py:102
msgid "This server ID no longer exists"
msgstr ""

#: ../server/importlib/userAuth.py:109
msgid "You are not authorized to manage packages in the null org"
msgstr ""

#: ../server/importlib/userAuth.py:115
#, python-format
msgid "You are not allowed to manage packages in the %s org"
msgstr ""

#. ok, you're a regular user who doesn't manage any channels.
#. take a hike.
#: ../server/importlib/userAuth.py:132
msgid "You are not allowed to perform administrative tasks"
msgstr ""

#: ../server/importlib/userAuth.py:159
#, python-format
msgid ""
"You are not allowed to manage channel %s, or that channel does not exist"
msgstr ""

#: ../server/importlib/userAuth.py:229
#, python-format
msgid ""
"\n"
"               %s Account has been deactivated on this server.\n"
"               Please contact your Org administrator for more help."
msgstr ""

#: ../server/rhnChannel.py:2217
#, python-format
msgid ""
"Your account does not have access to any channels matching "
"(release='%(release)s', arch='%(arch)s')%(www_activation)s"
msgstr ""

#: ../server/rhnChannel.py:2236
#, python-format
msgid "Insufficient subscription permissions for release (%s, %s"
msgstr ""

#. Various messages that can be reused
#.
#. bretm 02/07/2007 -- when we have better old-client documentation, probably
#. will be safe to get rid of all this crap
#: ../server/rhnChannel.py:2550 ../server/rhnChannel.py:2569
msgid "System Registered but Inactive"
msgstr ""

#: ../server/rhnChannel.py:2552
#, python-format
msgid ""
"\n"
"Invalid Architecture and OS release combination (%s, %s).\n"
"Your system has been registered, but will not receive updates\n"
"because it could not be subscribed to a base channel.\n"
"Please contact your organization administrator for assistance.\n"
msgstr ""

#: ../server/rhnChannel.py:2561
#, python-format
msgid ""
"\n"
"  This system has been successfully registered, but is not yet entitled\n"
"  to service.  To entitle this system to service, login to the web site at:\n"
"\n"
"  %(entitlement_url)s\n"
msgstr ""

#: ../server/rhnChannel.py:2571
#, python-format
msgid ""
"\n"
"  This system has been successfully registered, but no service entitlements\n"
"  were available.  To entitle this system to service, login to the web site "
"at:\n"
"\n"
"  %(entitlement_url)s\n"
msgstr ""

#. Invalid server certificate.
#: ../server/rhnHandler.py:62
msgid "Please run rhn_register as root on this client"
msgstr ""

#: ../server/rhnHandler.py:76
#, python-format
msgid "Service not enabled for system profile: \"%s\""
msgstr ""

#: ../server/rhnPackage.py:52 ../server/rhnPackage.py:98
#: ../server/rhnPackage.py:118 ../server/rhnPackage.py:179
#, python-format
msgid "Invalid RPM package %s requested"
msgstr ""

#: ../server/rhnPackage.py:124
msgid "Package not found"
msgstr ""

#: ../server/rhnServer/server_class.py:103
#, python-format
msgid "Architecture `%s' is not supported"
msgstr ""

#: ../server/rhnServer/server_token.py:86
#, python-format
msgid "Token `%s' has more than one base channel assigned"
msgstr ""

#: ../server/rhnServer/server_token.py:89
msgid "Conflicting base channels"
msgstr ""

#: ../server/rhnServer/server_token.py:223
#, python-format
msgid "Failed to add server to group %s"
msgstr ""

#: ../server/rhnServer/server_token.py:574
#, python-format
msgid "Maximum usage count of %s reached"
msgstr ""

#: ../server/rhnServer/server_token.py:869
msgid ""
"Stacking of re-registration tokens with different base entitlements is not "
"supported"
msgstr ""

#: ../server/rhnServer/server_token.py:946
#, python-format
msgid "Could not find token '%s'"
msgstr ""

#. Cannot use activation keys from different orgs
#: ../server/rhnServer/server_token.py:979
msgid "Tokens from mismatching orgs"
msgstr ""

#. Two tokens with different kickstart sessions
#: ../server/rhnServer/server_token.py:989
msgid "Kickstart session mismatch"
msgstr ""

#: ../server/rhnServer/server_token.py:1013
msgid "Stacking of re-registration tokens is not supported"
msgstr ""

#: ../server/rhnUser.py:327 ../server/rhnUser.py:330
msgid "Invalid username/password combination"
msgstr ""

#. nope, not reserved either
#: ../server/rhnUser.py:527
#, python-format
msgid "Username `%s' has not been reserved"
msgstr ""

#. New accounts have to specify an e-mail address
#: ../server/rhnUser.py:533
msgid "E-mail address not specified"
msgstr ""

#: ../server/rhnUser.py:575
#, python-format
msgid "username should be at least %d characters"
msgstr ""

#: ../server/rhnUser.py:579
#, python-format
msgid "username should be less than %d characters"
msgstr ""

#: ../server/rhnUser.py:593
#, python-format
msgid "username = `%s', invalid character `%s'"
msgstr ""

#: ../server/rhnUser.py:614
#, python-format
msgid "Please limit your e-mail address to %s chars"
msgstr ""

#: ../server/rhnUser.py:704
#, python-format
msgid "password must be at least %d characters"
msgstr ""

#: ../server/rhnUser.py:708
#, python-format
msgid "Password must be shorter than %d characters"
msgstr ""

#: ../server/rhnUser.py:724
#, python-format
msgid "password contains character `%s'"
msgstr ""

#: ../server/rhnUser.py:733
#, python-format
msgid "username should be at least %d characters long"
msgstr ""

#: ../server/rhnUser.py:744
#, python-format
msgid "Cannot register usernames ending with %s"
msgstr ""

#. 0-999: Red Hat client/client-like interaction errors:
#: ../common/rhnException.py:55
msgid "This does not appear to be a valid username."
msgstr ""

#: ../common/rhnException.py:56
msgid "Invalid username and password combination."
msgstr ""

#: ../common/rhnException.py:57
msgid "This login is already taken, or the password is incorrect."
msgstr ""

#: ../common/rhnException.py:58
msgid "Permission denied."
msgstr ""

#: ../common/rhnException.py:59
msgid "Object not found."
msgstr ""

#: ../common/rhnException.py:60
msgid "Invalid System Digital ID."
msgstr ""

#: ../common/rhnException.py:61
msgid "Invalid System Credentials."
msgstr ""

#: ../common/rhnException.py:62
msgid "Could not retrieve user data from database."
msgstr ""

#: ../common/rhnException.py:63
msgid "Valid username required."
msgstr ""

#: ../common/rhnException.py:64
msgid "Valid password required."
msgstr ""

#: ../common/rhnException.py:65
msgid "Minimum username length violation."
msgstr ""

#: ../common/rhnException.py:66
msgid "Minimum password length violation."
msgstr ""

#: ../common/rhnException.py:67
msgid "The username contains invalid characters."
msgstr ""

#: ../common/rhnException.py:68
msgid "File not found."
msgstr ""

#: ../common/rhnException.py:69
msgid "Architecture and OS version combination is not supported."
msgstr ""

#: ../common/rhnException.py:70
msgid "Could not retrieve system data from database."
msgstr ""

#: ../common/rhnException.py:71
msgid "Invalid arguments passed to function."
msgstr ""

#: ../common/rhnException.py:72
msgid "Unable to retrieve requested entry."
msgstr ""

#: ../common/rhnException.py:73
msgid "Could not update database entry."
msgstr ""

#: ../common/rhnException.py:74
msgid "Unsupported server architecture."
msgstr ""

#: ../common/rhnException.py:76
#, python-format
msgid ""
"\n"
"     The anonymous server functionality is no longer available.\n"
"\n"
"     Please re-register this system by running mgr_register as root.\n"
"     Please visit https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     or login at https://%(hostname)s, and from the \"Overview\" tab,\n"
"     select \"Subscription Management\" to enable the service for this "
"system.\n"
"     "
msgstr ""

#: ../common/rhnException.py:85
msgid "Record not available in the database."
msgstr ""

#: ../common/rhnException.py:86
msgid "Invalid value for entry."
msgstr ""

#: ../common/rhnException.py:88
#, python-format
msgid ""
"\n"
"     This system does not have a valid entitlement for SUSE Multi-Linux "
"Manager.\n"
"     Please visit https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     or login at https://%(hostname)s, and from the \"Overview\" tab,\n"
"     select \"Subscription Management\" to enable the service for this "
"system.\n"
"     "
msgstr ""

#: ../common/rhnException.py:95
msgid "Channel error"
msgstr ""

#: ../common/rhnException.py:96
msgid "Client session token is invalid."
msgstr ""

#: ../common/rhnException.py:97
msgid "Client session token has expired."
msgstr ""

#: ../common/rhnException.py:98
msgid "You are not authorized to retrieve the requested object."
msgstr ""

#: ../common/rhnException.py:99
msgid "Invalid action"
msgstr ""

#: ../common/rhnException.py:101
msgid "You are not allowed to perform administrative tasks on this system."
msgstr ""

#: ../common/rhnException.py:104
msgid "The system is already subscribed to the specified channel."
msgstr ""

#: ../common/rhnException.py:105
msgid "The system is not currently subscribed to the specified channel."
msgstr ""

#: ../common/rhnException.py:106
msgid "The specified channel does not exist."
msgstr ""

#: ../common/rhnException.py:107
msgid "Invalid channel version."
msgstr ""

#: ../common/rhnException.py:109
msgid ""
"\n"
"     User group membership limits exceeded.\n"
"\n"
"     The current settings for your account do not allow you to add another\n"
"     user account. Please check with the organization administrator for "
"your\n"
"     account if the maximum number of users allowed to subscribe to server "
"needs\n"
"     to be changed.\n"
"     "
msgstr ""

#: ../common/rhnException.py:119
msgid ""
"\n"
"     System group membership limits exceeded.\n"
"\n"
"     The current settings for your account do not allow you to add another\n"
"     system profile. Please check with the organization administrator for "
"your\n"
"     account for modifying the maximum number of system profiles that can "
"be\n"
"     subscribed to your account.\n"
"     "
msgstr ""

#: ../common/rhnException.py:129
msgid ""
"\n"
"     Invalid architecture.\n"
"\n"
"     The architecture of the package is not supported by\n"
"     "
msgstr ""

#: ../common/rhnException.py:136
msgid "Invalid RPM header"
msgstr ""

#: ../common/rhnException.py:138
msgid ""
"\n"
"    This system is already registered as a Salt Minion. If you want to "
"register it as a traditional client\n"
"    please delete it first via the web UI or API and then register it using "
"the traditional tools.\n"
"    "
msgstr ""

#. For the uploading tools
#: ../common/rhnException.py:144
msgid "Invalid information uploaded to the server"
msgstr ""

#: ../common/rhnException.py:145
msgid "Error uploading network interfaces configuration."
msgstr ""

#: ../common/rhnException.py:147
msgid ""
"\n"
"     Package Upload Failed due to uniqueness constraint violation.\n"
"     Make sure the package does not have any duplicate dependencies or\n"
"     does not already exists on the server\n"
"     "
msgstr ""

#: ../common/rhnException.py:154
msgid ""
"\n"
"     The --force mgrpush option is disabled on this server.\n"
"     Please contact your SUSE Multi-Linux Manager administrator for more "
"help.\n"
"     "
msgstr ""

#: ../common/rhnException.py:161
msgid ""
"\n"
"     The activation token specified could not be found on the server.\n"
"     Please retry with a valid key.\n"
"     "
msgstr ""

#: ../common/rhnException.py:166
msgid "Too many systems registered using this registration token"
msgstr ""

#: ../common/rhnException.py:167
msgid "Token contains invalid, obsoleted or insufficient settings"
msgstr ""

#: ../common/rhnException.py:168
msgid "Conflicting activation tokens"
msgstr ""

#: ../common/rhnException.py:171
msgid ""
"\n"
"     No matching base channel found for your system.\n"
"     "
msgstr ""

#: ../common/rhnException.py:176
msgid ""
"\n"
"     You do not have subscription permission to the designated channel.\n"
"     Please refer to your organization's channel or organization\n"
"     administrators for further details.\n"
"     "
msgstr ""

#: ../common/rhnException.py:182
msgid "You can not unsubscribe from base channel."
msgstr ""

#: ../common/rhnException.py:183
msgid "SUSE Multi-Linux Manager or Proxy channel can not be subscribed."
msgstr ""

#. 80-90: server group errors
#: ../common/rhnException.py:185
msgid "There was an error while trying to join the system to its groups"
msgstr ""

#. 90-100: entitlement errors
#: ../common/rhnException.py:187
msgid "Unable to entitle system"
msgstr ""

#. 100-109: e-mail and uuid related faults
#: ../common/rhnException.py:189
msgid "Maximum e-mail length violation."
msgstr ""

#: ../common/rhnException.py:190
msgid "This system has been previously registered."
msgstr ""

#: ../common/rhnException.py:191
msgid "Invalid username"
msgstr ""

#. 140-159 applet errors
#: ../common/rhnException.py:193
msgid "Unable to look up server"
msgstr ""

#. 160-179: OSAD errors
#: ../common/rhnException.py:195
msgid "Required argument is missing"
msgstr ""

#. 600-699: RHEL5+ EN errors
#: ../common/rhnException.py:197
msgid "No entitlement information tied to hardware"
msgstr ""

#: ../common/rhnException.py:198
msgid "Installation number is not entitling"
msgstr ""

#. 700-799: Additional user input verification errors.
#: ../common/rhnException.py:200
msgid "Maximum username length violation"
msgstr ""

#: ../common/rhnException.py:201
msgid "Maximum password length violation"
msgstr ""

#: ../common/rhnException.py:202
msgid "This user has read only API access. Action denied."
msgstr ""

#: ../common/rhnException.py:203
msgid "System Name cannot be less than 1 character"
msgstr ""

#. 1000-1999: Proxy specific errors:
#. issued by a Proxy to the client
#: ../common/rhnException.py:206
msgid "SUSE Multi-Linux Manager Proxy error."
msgstr ""

#: ../common/rhnException.py:207
msgid "SUSE Multi-Linux Manager Proxy unable to login."
msgstr ""

#: ../common/rhnException.py:210
msgid ""
"\n"
"     SUSE Multi-Linux Manager Proxy system ID does not match a Spacewalk "
"Proxy Server\n"
"     in the database.\n"
"     "
msgstr ""

#: ../common/rhnException.py:215
msgid "SUSE Multi-Linux Manager Proxy session token is invalid."
msgstr ""

#: ../common/rhnException.py:216
msgid "SUSE Multi-Linux Manager Proxy session token has expired."
msgstr ""

#: ../common/rhnException.py:220
msgid ""
"\n"
"      user creation is not allowed via mgr_register;\n"
"     please contact your sysadmin to have your account created.\n"
"     "
msgstr ""

#: ../common/rhnException.py:226
msgid ""
"\n"
"     This SUSE Multi-Linux Manager server is not allowed to use Inter Server "
"Sync on this server\n"
"     "
msgstr ""

#: ../common/rhnException.py:231
msgid ""
"\n"
"     Inter Server Sync is disabled on this SUSE Multi-Linux Manager Server.\n"
"     "
msgstr ""

#. 3000-3999: XML dumper errors:
#: ../common/rhnException.py:236
msgid "Invalid datatype passed"
msgstr ""

#: ../common/rhnException.py:237
msgid "Unable to retrieve channel"
msgstr ""

#: ../common/rhnException.py:238
msgid "Unable to retrieve package"
msgstr ""

#: ../common/rhnException.py:239
msgid "Unable to retrieve erratum"
msgstr ""

#: ../common/rhnException.py:240
msgid "File is missing"
msgstr ""

#: ../common/rhnException.py:241
msgid "Function retrieval error"
msgstr ""

#: ../common/rhnException.py:242
msgid "Function execution error"
msgstr ""

#: ../common/rhnException.py:243
msgid "Missing version string"
msgstr ""

#: ../common/rhnException.py:244
msgid "Invalid version string"
msgstr ""

#: ../common/rhnException.py:245
msgid "Mismatching versions"
msgstr ""

#: ../common/rhnException.py:246
msgid "Invalid channel version"
msgstr ""

#: ../common/rhnException.py:247
msgid "No comps file for channel"
msgstr ""

#: ../common/rhnException.py:248
msgid "Unable to retrieve comps file"
msgstr ""

#. 4000 - 4999: config management errors
#: ../common/rhnException.py:250
msgid "Configuration action missing"
msgstr ""

#: ../common/rhnException.py:251
msgid "File too large"
msgstr ""

#: ../common/rhnException.py:252
msgid "File contains binary data"
msgstr ""

#: ../common/rhnException.py:253
msgid "Configuration channel is not empty"
msgstr ""

#: ../common/rhnException.py:254
msgid "Permission error"
msgstr ""

#: ../common/rhnException.py:255
msgid "Content missing for configuration file"
msgstr ""

#: ../common/rhnException.py:256
msgid "Template delimiters not specified"
msgstr ""

#: ../common/rhnException.py:257
msgid "Configuration channel does not exist"
msgstr ""

#: ../common/rhnException.py:258
msgid "Configuration channel already exists"
msgstr ""

#: ../common/rhnException.py:259
msgid "File missing from configuration channel"
msgstr ""

#: ../common/rhnException.py:260
msgid "Different revision of this file is uploaded"
msgstr ""

#: ../common/rhnException.py:261
msgid "File already uploaded to configuration channel"
msgstr ""

#: ../common/rhnException.py:262
msgid "File size exceeds remaining quota space"
msgstr ""

#: ../common/rhnException.py:263
msgid "Full path of file must be specified"
msgstr ""

#: ../common/rhnException.py:264
msgid "Invalid revision number"
msgstr ""

#: ../common/rhnException.py:265
msgid "Cannot compare files of different file type"
msgstr ""

#. 5100 - 5199: scap results reporting error
#: ../common/rhnException.py:267
msgid "SCAP results file transfer is invalid or incomplete"
msgstr ""

#: ../common/rhnException.py:268
msgid "Error composing directory path for detailed SCAP results"
msgstr ""

#: ../common/rhnException.py:269
msgid "Error composing file path for detailed SCAP results"
msgstr ""

#: ../common/rhnException.py:270
msgid "Invalid content encoding"
msgstr ""

#: ../common/rhnException.py:317
msgid ""
"\n"
"     An error has occurred while processing your request. If this problem\n"
"     persists please enter a bug report at scc.suse.com.\n"
"     If you choose to submit the bug report, please be sure to include\n"
"     details of what you were trying to do when this error occurred and\n"
"     details on how to reproduce this problem.\n"
msgstr ""

#: ../common/rhnException.py:368
#, python-format
msgid ""
"Error Message:\n"
"    %s\n"
msgstr ""

#: ../common/rhnException.py:370
#, python-format
msgid "Error Class Code: %s\n"
msgstr ""

#: ../common/rhnException.py:373
#, python-format
msgid "Error Class Info: %s\n"
msgstr ""

#: ../common/rhnException.py:375
#, python-format
msgid "Explanation: %s"
msgstr ""

#: ../common/rhnTB.py:220
#, python-format
msgid "ERROR: %s %s: %s"
msgstr ""

#: ../common/rhnTB.py:221
#, python-format
msgid "TRACEBACK: %s"
msgstr ""

#: ../satellite_tools/disk_dumper/iss.py:1634
#: ../satellite_tools/disk_dumper/iss.py:1640
#, python-format
msgid "format of %s should be at least YYYYMMDD.\n"
msgstr ""

#: ../satellite_tools/messages.py:28
#, python-format
msgid ""
"\n"
"ERROR: executing step %s. Error is:\n"
"%s\n"
msgstr ""

#: ../satellite_tools/messages.py:35
#, python-format
msgid ""
"\n"
"ERROR: there was a problem accessing the channel data from your temporary\n"
"       repository. Did you migrate all of the data from the channel ISOs\n"
"       do this directory? If so, please recheck the channels ISOs, ensure\n"
"       that you have them all, and then iteratively remount and repopulate\n"
"       the temporary repository (%s).\n"
msgstr ""

#: ../satellite_tools/messages.py:45
#, python-format
msgid ""
"\n"
"ERROR: there was a problem synchronizing the information.\n"
"       Error message: %s\n"
msgstr ""

#: ../satellite_tools/messages.py:52
#, python-format
msgid ""
"\n"
"ERROR: There was a problem communicating with the ISS Master.\n"
"       Depending on the specific error details, please review your "
"configuration,\n"
"       basic network connectivity, and/or name resolution, and try again.\n"
"       Error message: %s\n"
msgstr ""

#: ../satellite_tools/messages.py:61
#, python-format
msgid ""
"\n"
"ERROR: a child-channel cannot be synced without its parent being synced as\n"
"       well. A parent needs to be either (a) previously synced or (b) "
"synced\n"
"       in tandem with the desired child-channel. Missing parents for this\n"
"       transaction:\n"
"       %s\n"
msgstr ""

#: ../satellite_tools/messages.py:71
#, python-format
msgid ""
"\n"
"ERROR: you are not entitled to sync a channel in this set of channels.\n"
"Please contact your SUSE Multi-Linux Manager contact\n"
"%s"
msgstr ""

#: ../satellite_tools/messages.py:77
#, python-format
msgid "  ERROR: not enough free space (%s KB) on device."
msgstr ""

#: ../satellite_tools/messages.py:79
#, python-format
msgid "    %3d/%s Fetch successful: %s (%s bytes)"
msgstr ""

#: ../satellite_tools/messages.py:80
#, python-format
msgid "    Extinct package:  %s"
msgstr ""

#: ../satellite_tools/messages.py:81
#, python-format
msgid "   Total size: %s"
msgstr ""

#: ../satellite_tools/messages.py:83
#, python-format
msgid "      Downloaded %s of %s. Estimated remaining time: %s"
msgstr ""

#: ../satellite_tools/messages.py:85
#, python-format
msgid "    Fetch unsuccessful: %s"
msgstr ""

#: ../satellite_tools/messages.py:86
#, python-format
msgid "   RPM fetch summary: %s"
msgstr ""

#: ../satellite_tools/messages.py:87
#, python-format
msgid "       success: %d"
msgstr ""

#: ../satellite_tools/messages.py:88
#, python-format
msgid "       failed:  %d"
msgstr ""

#: ../satellite_tools/messages.py:89
#, python-format
msgid "       extinct: %d"
msgstr ""

#: ../satellite_tools/messages.py:91
#, python-format
msgid "   Retrieving / parsing *relevant* package metadata: %s (%s)"
msgstr ""

#: ../satellite_tools/messages.py:92
#, python-format
msgid "   Retrieving / parsing errata data: %s (%s)"
msgstr ""

#: ../satellite_tools/messages.py:93
#, python-format
msgid "   Retrieving / parsing kickstart data: %s (%s)"
msgstr ""

#: ../satellite_tools/messages.py:94
#, python-format
msgid "   Retrieving / parsing kickstart tree files: %s (%s)"
msgstr ""

#: ../satellite_tools/messages.py:95
#, python-format
msgid "   Importing *relevant* package metadata: %s (%s)"
msgstr ""

#: ../satellite_tools/messages.py:96
msgid "   * WARNING: this may be a slow process."
msgstr ""

#: ../satellite_tools/messages.py:97
msgid "Linking packages to channels"
msgstr ""

#: ../satellite_tools/messages.py:98
#, python-format
msgid "   Importing *relevant* errata: %s (%s)"
msgstr ""

#: ../satellite_tools/messages.py:99
msgid "   No new kickstartable tree to import"
msgstr ""

#: ../satellite_tools/messages.py:100
#, python-format
msgid "Importing kickstartable trees (%d)"
msgstr ""

#: ../satellite_tools/messages.py:101
#, python-format
msgid "Imported kickstartable trees (%d)"
msgstr ""

#: ../satellite_tools/reposync.py:138
msgid "+++ sending log as an email +++"
msgstr ""

#: ../satellite_tools/reposync.py:141
#, python-format
msgid "%s sync. report from %s"
msgstr ""

#: ../satellite_tools/reposync.py:151
msgid "+++ email requested, but there is nothing to send +++"
msgstr ""
